#!/bin/bash
#
# Build Release Archives
# Creates standalone and framework distribution packages
#

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
RELEASE_DIR="${PROJECT_DIR}/release"

cd "$PROJECT_DIR"

echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Building Claude Export Release Packages"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Step 1: Build TypeScript
echo "Step 1: Compiling TypeScript..."
npm run build
echo "   → dist/ ready"

# Step 2: Prepare staging directories
echo ""
echo "Step 2: Preparing staging directories..."
rm -rf "${RELEASE_DIR}/standalone" "${RELEASE_DIR}/framework"
mkdir -p "${RELEASE_DIR}/standalone/.claude-export"
mkdir -p "${RELEASE_DIR}/framework/.claude-export"
mkdir -p "${RELEASE_DIR}/framework/.claude/commands"

# Step 3: Copy standalone files
echo ""
echo "Step 3: Building standalone package..."
cp -r dist "${RELEASE_DIR}/standalone/.claude-export/"
cp -r html-viewer "${RELEASE_DIR}/standalone/.claude-export/"
echo "   → .claude-export/dist/"
echo "   → .claude-export/html-viewer/"

# Step 4: Copy framework files (includes standalone + extras)
echo ""
echo "Step 4: Building framework package..."
cp -r dist "${RELEASE_DIR}/framework/.claude-export/"
cp -r html-viewer "${RELEASE_DIR}/framework/.claude-export/"

# Copy framework meta-files (create clean templates)
cat > "${RELEASE_DIR}/framework/CLAUDE.md" << 'CLAUDEMD'
# Project Context for Claude Code

> This file is automatically loaded into every Claude Code session

---

## Quick Start

This project uses **Claude Export** for dialog history management.

### Available Commands

```bash
npm run dialog:export  # Export dialogs + generate HTML
npm run dialog:ui      # Start web UI on :3333
npm run dialog:list    # List all sessions
```

### Sprint Completion Protocol

When finishing a work session, say: **"Завершить спринт"** (or "Finish sprint")

Claude will:
1. Run `npm run dialog:export`
2. Update documentation
3. Create git commit
4. Push changes

---

## Project Structure

```
project/
├── .claude-export/      # Export utility (do not modify)
├── .dialog/             # Exported dialogs (auto-generated)
├── dialog-viewer/       # Static HTML viewer for sharing
└── CLAUDE.md            # This file
```

---

## Customization

Add your project-specific instructions below:

### Project Description
<!-- Describe your project here -->

### Key Files
<!-- List important files -->

### Coding Standards
<!-- Your coding conventions -->

---

*Generated by Claude Export v2.3.0*
CLAUDEMD

cat > "${RELEASE_DIR}/framework/PROCESS.md" << 'PROCESSMD'
# Sprint Completion Protocol

> Checklist for finishing a work session

---

## Checklist

### 1. Export Dialogs
- [ ] `npm run dialog:export` — export sessions + generate HTML
- [ ] Check `dialog-viewer/index.html` (optional)

### 2. Update Documentation
- [ ] Update relevant .md files
- [ ] Add changelog entry if needed

### 3. Git Commit & Push
- [ ] `git add .`
- [ ] `git commit -m "feat: description"`
- [ ] `git push`

---

## Completion Criteria

A sprint is complete when:
1. Code compiles without errors
2. Functionality is tested
3. Dialogs are exported
4. Changes are committed and pushed

---

*Generated by Claude Export v2.3.0*
PROCESSMD

# Copy slash command
cat > "${RELEASE_DIR}/framework/.claude/commands/ui.md" << 'UIMD'
Запусти Web UI для просмотра и управления диалогами Claude Export.

Выполни команду:
```bash
npm run dialog:ui
```

После запуска:
- Открой http://localhost:3333 в браузере
- UI позволяет просматривать диалоги и управлять их видимостью
- Для остановки: Ctrl+C
UIMD

echo "   → .claude-export/dist/"
echo "   → .claude-export/html-viewer/"
echo "   → CLAUDE.md"
echo "   → PROCESS.md"
echo "   → .claude/commands/ui.md"

# Step 5: Create archives
echo ""
echo "Step 5: Creating archives..."

cd "${RELEASE_DIR}/standalone"
tar -czf "../claude-export-standalone.tar.gz" .claude-export
echo "   → claude-export-standalone.tar.gz"

cd "${RELEASE_DIR}/framework"
tar -czf "../claude-export-framework.tar.gz" .claude-export .claude CLAUDE.md PROCESS.md
echo "   → claude-export-framework.tar.gz"

# Step 6: Copy install script
echo ""
echo "Step 6: Preparing installer..."
cp "${RELEASE_DIR}/install.sh" "${RELEASE_DIR}/install-standalone.sh"
cp "${RELEASE_DIR}/install.sh" "${RELEASE_DIR}/install-framework.sh"
chmod +x "${RELEASE_DIR}/install-standalone.sh"
chmod +x "${RELEASE_DIR}/install-framework.sh"
chmod +x "${RELEASE_DIR}/install.sh"

# Show results
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "  Build Complete!"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Release files in: ${RELEASE_DIR}"
echo ""
echo "Standalone (utility only):"
ls -lh "${RELEASE_DIR}/claude-export-standalone.tar.gz" | awk '{print "  " $9 " (" $5 ")"}'
echo ""
echo "Framework (full automation):"
ls -lh "${RELEASE_DIR}/claude-export-framework.tar.gz" | awk '{print "  " $9 " (" $5 ")"}'
echo ""
echo "Installation:"
echo "  1. Copy install.sh + archive to target project"
echo "  2. Run: ./install.sh (standalone) or ./install.sh --framework"
echo ""
